spring.application.name=comment-service
server.port=8086

# Database
spring.datasource.url=jdbc:mysql://localhost:3306/flowboard_comment?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=123Kanhiya@
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# JWT — must match across ALL services
jwt.secret=mysecretkeymysecretkeymysecretkey
jwt.expiration=86400000

# Inter-service URLs
auth.service.url=http://localhost:8081
card.service.url=http://localhost:8085

# RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# Notification exchange config
rabbitmq.exchange=flowboard.exchange
rabbitmq.notification.routing-key=notification.event

logging.level.com.flowboard=DEBUG
