spring.application.name=workspace-service
server.port=8082

spring.datasource.url=jdbc:mysql://localhost:3306/flowboard_workspace?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=123Kanhiya@
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# JWT - must match auth-service exactly
jwt.secret=mysecretkeymysecretkeymysecretkey
jwt.expiration=86400000

# Auth service URL (to resolve email -> userId)
auth.service.url=http://localhost:8081
